# -*- coding: utf-8 -*-
"""01_eda.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNAGYHw254UuMcfATsBaxM0zjMezoqEJ
"""

import pandas as pd
import seaborn as sns
import numpy as np

df = sns.load_dataset("titanic")

df.head()

"""Part A — Profiling, cleaning, and the data story

Task 1: Profiling
"""

df.info()

df.describe()

df.shape

df.isnull().sum()

missing_pct = df.isnull().mean() * 100
missing_percent = missing_pct[missing_pct > 0]
print(missing_percent)

df.to_csv("titanic.csv", index=False)

"""Task 2:
a. If data is under 5% missing → drop those rows;
b. 5%–30% missing → impute
c. for any column whose missing rate is so high that imputation would be unreliable, explicitly decide to either drop the column or encode "missing" as its own category
"""

# drop rows for embarked and embark_town as its percentage is 0.22% which is less than 5%
df = df.dropna(subset = ['embarked','embark_town'])

# impute age with median as its missing percentage is 19.8% which is in between 5-30%. Min age is 0.4 and max is 80
# For age imputation, median is considered instead of mean as the age distribution is skewed and  Mean will get pulled upwards by the outliers.
# As the median is less sensitive to the extreme values, considerng media.
df['age'] = df['age'].fillna(df['age'].median())

# Encode missing as deck category as its missing percent is higher than 30%
df['deck'] = df['deck'].astype('category')
df['deck'] = df['deck'].cat.add_categories(['Missing']).fillna('Missing')

missing_pct = df.isnull().mean() * 100
missing_percent = missing_pct[missing_pct > 0]
print(missing_percent)

"""Task 3: Univariate analysis"""

import matplotlib.pyplot as plt

# Histogram for age
plt.figure(figsize = (6,4))
plt.hist(df['age'], bins = 30, color = 'skyblue', edgecolor = 'black')

plt.title('Age Histogram')
plt.xlabel('Age')
plt.ylabel('Count')

plt.show()

# Histogram for fare
plt.figure(figsize = (6,4))
plt.hist(df['fare'], bins = 30, color = 'skyblue', edgecolor = 'black')

plt.title('fare Histogram')
plt.xlabel('Fare')
plt.ylabel('Count')

plt.show()

plt.figure(figsize = (6,4))
plt.boxplot(df['age'], vert = False)

plt.title('Age Box Plot')
plt.xlabel('Age')
plt.show()

plt.figure(figsize = (6,4))
plt.boxplot(df['fare'], vert = False)

plt.title('Fare Box Plot')
plt.xlabel('fare')
plt.show()

"""quartile computation"""

# Approx age
Q1 = 21
Q3 = 35
# Approx fare
Q1 = 10
Q3 = 30

IQR = Q3-Q1
Age_IQR = 15
fare_IQR = 20

Lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

Age_bound = [-1.5, 57.5]
fare_bound = [-20,60]

print(f'age outliers: {len(df[df['age']>=58])}')

print(f'fare outliers: {len(df[df['fare']>=60])}')

print(f'Fare mean: {df['fare'].mean():.2f}')
print(f'Fare median: {df['fare'].median():.2f}')
print(f'Fare mode: {df['fare'].mode()[0]}')

"""since fare mean>median>mode, fare distribution is right-skewed

Task 4: Bivariate analysis
"""

# survival rte by sex
survival_by_sex = df.groupby('sex')['survived'].mean()
print("Survival rate by sex:\n", survival_by_sex)

# Survival rate by pclass
survival_by_pclass = df.groupby('pclass')['survived'].mean()
print("Survival rate by pclass:\n", survival_by_pclass)

# Survival rate by sex and pclass together
survival_by_sex_pclass = df.groupby(['sex','pclass'])['survived'].mean()
print("Survival rate by sex and pclass:\n", survival_by_sex_pclass)

"""Correlation Matrix"""

# numeric columns
numeric_cols = ["survived","pclass","age","sibsp","parch","fare"]

corr_matrix = df[numeric_cols].corr()

# Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", center=0)
plt.title("Correlation Matrix - 6 numeric features")
plt.show()

"""If rank all off-diagonal correlations by absolute value, the two strongest correlations are:

1. pclass vs fare: This is having Strong negative correlation. As higher class corresponds to higher fares and lower class corresponds to lower fares.

2. sibsp vs parch: This is having positive correlation. As passengers with siblings/spouses traveled with parents/children.

Task 5: Multivariate analysis
"""

# survival rate by pclass - bar chart
sns.barplot(x="pclass", y="survived", data=df)
plt.title("Survival Rate by Passenger Class")
plt.show()

# Age Distribution by Survval - box plot
sns.boxplot(x="survived", y="age", data=df)
plt.title("Age Distribution by Survival")
plt.show()

# heatmap
numeric_cols = ["survived","pclass","age","sibsp","parch","fare"]
corr_matrix = df[numeric_cols].corr()

sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", center=0)
plt.title("Correlation Matrix (6 Numeric Features)")
plt.show()

# Fare vs Age by Survival -- scatter plot
sns.scatterplot(x="age", y="fare", hue="survived", data=df, alpha=0.7)
plt.title("Fare vs Age by Survival")
plt.show()

# pair plot
sns.pairplot(df[["survived","age","fare","pclass","sex"]], hue="survived")
plt.show()

"""Task 6: exploratory Check"""

!pip3 install scikit-learn

from sklearn.preprocessing import StandardScaler

print("Before scaling:")
print(df[["age","fare"]].agg(["mean","std"]))

# Standardize using z-score formula
scaler = StandardScaler()
df[["age_scaled","fare_scaled"]] = scaler.fit_transform(df[["age","fare"]])

print("\nAfter scaling:")
print(df[["age_scaled","fare_scaled"]].agg(["mean","std"]))