# -*- coding: utf-8 -*-
"""Capstone_Module_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNAGYHw254UuMcfATsBaxM0zjMezoqEJ
"""

import pandas as pd
import seaborn as sns
import numpy as np

df = sns.load_dataset("titanic")

df.head()

"""Part A — Profiling, cleaning, and the data story

Task 1: Profiling
"""

df.info()

df.describe()

df.shape

df.isnull().sum()

missing_pct = df.isnull().mean() * 100
missing_percent = missing_pct[missing_pct > 0]
print(missing_percent)

df.to_csv("titanic.csv", index=False)

"""Task 2:
a. If data is under 5% missing → drop those rows;
b. 5%–30% missing → impute
c. for any column whose missing rate is so high that imputation would be unreliable, explicitly decide to either drop the column or encode "missing" as its own category
"""

# drop rows for embarked and embark_town as its percentage is 0.22% which is less than 5%
df = df.dropna(subset = ['embarked','embark_town'])

# impute age with median as its missing percentage is 19.8% which is in between 5-30%. Min age is 0.4 and max is 80
# For age imputation, median is considered instead of mean as the age distribution is skewed and  Mean will get pulled upwards by the outliers.
# As the median is less sensitive to the extreme values, considerng media.
df['age'] = df['age'].fillna(df['age'].median())

# Encode missing as deck category as its missing percent is higher than 30%
df['deck'] = df['deck'].astype('category')
df['deck'] = df['deck'].cat.add_categories(['Missing']).fillna('Missing')

missing_pct = df.isnull().mean() * 100
missing_percent = missing_pct[missing_pct > 0]
print(missing_percent)

"""Task 3: Univariate analysis"""

import matplotlib.pyplot as plt

# Histogram for age
plt.figure(figsize = (6,4))
plt.hist(df['age'], bins = 30, color = 'skyblue', edgecolor = 'black')

plt.title('Age Histogram')
plt.xlabel('Age')
plt.ylabel('Count')

plt.show()

# Histogram for fare
plt.figure(figsize = (6,4))
plt.hist(df['fare'], bins = 30, color = 'skyblue', edgecolor = 'black')

plt.title('fare Histogram')
plt.xlabel('Fare')
plt.ylabel('Count')

plt.show()

plt.figure(figsize = (6,4))
plt.boxplot(df['age'], vert = False)

plt.title('Age Box Plot')
plt.xlabel('Age')
plt.show()

plt.figure(figsize = (6,4))
plt.boxplot(df['fare'], vert = False)

plt.title('Fare Box Plot')
plt.xlabel('fare')
plt.show()

"""quartile computation"""

# Approx age
Q1 = 21
Q3 = 35
# Approx fare
Q1 = 10
Q3 = 30

IQR = Q3-Q1
Age_IQR = 15
fare_IQR = 20

Lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

Age_bound = [-1.5, 57.5]
fare_bound = [-20,60]

print(f'age outliers: {len(df[df['age']>=58])}')

print(f'fare outliers: {len(df[df['fare']>=60])}')

print(f'Fare mean: {df['fare'].mean():.2f}')
print(f'Fare median: {df['fare'].median():.2f}')
print(f'Fare mode: {df['fare'].mode()[0]}')

"""since fare mean>median>mode, fare distribution is right-skewed

Task 4: Bivariate analysis
"""

# survival rte by sex
survival_by_sex = df.groupby('sex')['survived'].mean()
print("Survival rate by sex:\n", survival_by_sex)

# Survival rate by pclass
survival_by_pclass = df.groupby('pclass')['survived'].mean()
print("Survival rate by pclass:\n", survival_by_pclass)

# Survival rate by sex and pclass together
survival_by_sex_pclass = df.groupby(['sex','pclass'])['survived'].mean()
print("Survival rate by sex and pclass:\n", survival_by_sex_pclass)

"""Correlation Matrix"""

# numeric columns
numeric_cols = ["survived","pclass","age","sibsp","parch","fare"]

corr_matrix = df[numeric_cols].corr()

# Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", center=0)
plt.title("Correlation Matrix - 6 numeric features")
plt.show()

"""If rank all off-diagonal correlations by absolute value, the two strongest correlations are:

1. pclass vs fare: This is having Strong negative correlation. As higher class corresponds to higher fares and lower class corresponds to lower fares.

2. sibsp vs parch: This is having positive correlation. As passengers with siblings/spouses traveled with parents/children.

Task 5: Multivariate analysis
"""

# survival rate by pclass - bar chart
sns.barplot(x="pclass", y="survived", data=df)
plt.title("Survival Rate by Passenger Class")
plt.show()

# Age Distribution by Survval - box plot
sns.boxplot(x="survived", y="age", data=df)
plt.title("Age Distribution by Survival")
plt.show()

# heatmap
numeric_cols = ["survived","pclass","age","sibsp","parch","fare"]
corr_matrix = df[numeric_cols].corr()

sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", center=0)
plt.title("Correlation Matrix (6 Numeric Features)")
plt.show()

# Fare vs Age by Survival -- scatter plot
sns.scatterplot(x="age", y="fare", hue="survived", data=df, alpha=0.7)
plt.title("Fare vs Age by Survival")
plt.show()

# pair plot
sns.pairplot(df[["survived","age","fare","pclass","sex"]], hue="survived")
plt.show()

"""Task 6: exploratory Check"""

!pip3 install scikit-learn

from sklearn.preprocessing import StandardScaler

print("Before scaling:")
print(df[["age","fare"]].agg(["mean","std"]))

# Standardize using z-score formula
scaler = StandardScaler()
df[["age_scaled","fare_scaled"]] = scaler.fit_transform(df[["age","fare"]])

print("\nAfter scaling:")
print(df[["age_scaled","fare_scaled"]].agg(["mean","std"]))

"""Part B — Predictive modeling, continuing from the same cleaned data

Task 7: Train-Test Split using stratified split
"""

from sklearn.model_selection import train_test_split

# Features and Target
X = df.drop('survived', axis = 1)
y = df['survived']

# stratified split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

print("Train size:", X_train.shape[0])
print("Test size:", X_test.shape[0])
print("Class balance in full dataset:\n", y.value_counts(normalize=True))
print("Class balance in train set:\n", y_train.value_counts(normalize=True))
print("Class balance in test set:\n", y_test.value_counts(normalize=True))

"""The Titanic dataset is imbalanced. About 62% of passengers died and 38% survived.

If we split the data randomly without stratification, the train and test sets might not get equal survival proportions.

Stratified splitting ensures that both train and test sets gets the same class balance as the original dataset.

This is important for classification tasks: it prevents biased training

Task 8: Preprocessing
"""

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# Target and features
X = df.drop("survived", axis=1)
y = df["survived"]

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Define column groups
numeric_features = ["age", "fare", "sibsp", "parch"]
categorical_features = ["sex", "embarked"]

# Preprocessing for numeric columns: impute + scale
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),   # fill missing with median
    ("scaler", StandardScaler())                     # z-score scaling
])

# Preprocessing for categorical columns: impute + one-hot encode
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),  # fill missing with mode
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine into ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

# Full pipeline: preprocessing + model
clf = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

# Fit only on training data
clf.fit(X_train, y_train)

# Transform test data (no refitting!)
y_pred = clf.predict(X_test)

"""Task 9: Train three classifiers - Logistic Regression, Decision Tree, and Random Forest"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

# Logistic Regression pipeline
log_reg = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

# Decision Tree pipeline
tree_clf = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(max_depth=4, random_state=42))
])

# Random Forest pipeline
rf_clf = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(n_estimators=100, random_state=42))
])

# Fit models
log_reg.fit(X_train, y_train)
tree_clf.fit(X_train, y_train)
rf_clf.fit(X_train, y_train)

# Evaluate
print("Logistic Regression test accuracy:", log_reg.score(X_test, y_test))
print("Decision Tree test accuracy:", tree_clf.score(X_test, y_test))
print("Random Forest test accuracy:", rf_clf.score(X_test, y_test))

# Render Decision Tree
# Extract fitted tree from pipeline
fitted_tree = tree_clf.named_steps["classifier"]

# Get feature names after preprocessing
feature_names = tree_clf.named_steps["preprocessor"].get_feature_names_out()
class_names = ["died", "survived"]

plt.figure(figsize=(20,10))
plot_tree(fitted_tree, feature_names=feature_names, class_names=class_names,
          filled=True, rounded=True, fontsize=10)
plt.show()

"""Task 10: Evaluate all three models with: a confusion matrix, accuracy, precision, recall, F1 score, and an ROC curve with AUC"""

from sklearn.metrics import (
    confusion_matrix, accuracy_score, precision_score,
    recall_score, f1_score, roc_auc_score, roc_curve
)

models = {
    "Logistic Regression": log_reg,
    "Decision Tree": tree_clf,
    "Random Forest": rf_clf
}

results = []

plt.figure(figsize=(8,6))

for name, model in models.items():
    # Predictions
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title(f"Confusion Matrix: {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)

    results.append([name, acc, prec, rec, f1, auc])

    # ROC curve
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=f"{name} (AUC={auc:.2f})")

plt.plot([0,1],[0,1],"k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves")
plt.legend()
plt.show()

# Comparison table
metrics_df = pd.DataFrame(results, columns=["Model","Accuracy","Precision","Recall","F1","ROC-AUC"])
print(metrics_df)

"""Task 11: Imbalance handling comparison"""

print("Class balance:\n", y.value_counts(normalize=True))

from imblearn.over_sampling import SMOTE
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score
import pandas as pd

# Define preprocessing
numeric_features = ["age", "fare", "sibsp", "parch"]
categorical_features = ["sex", "embarked"]

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

# Fit preprocessor on training data only
X_train_proc = preprocessor.fit_transform(X_train)
X_test_proc = preprocessor.transform(X_test)

# (a) Baseline Logistic Regression
baseline = LogisticRegression(max_iter=1000)
baseline.fit(X_train_proc, y_train)
y_pred_base = baseline.predict(X_test_proc)

# (b) Class weight balanced
balanced = LogisticRegression(max_iter=1000, class_weight="balanced")
balanced.fit(X_train_proc, y_train)
y_pred_bal = balanced.predict(X_test_proc)

# (c) SMOTE oversampling (train only, after preprocessing)
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_proc, y_train)

smote_model = LogisticRegression(max_iter=1000)
smote_model.fit(X_train_res, y_train_res)
y_pred_smote = smote_model.predict(X_test_proc)

# Collect metrics
def metrics(y_true, y_pred):
    return [
        precision_score(y_true, y_pred),
        recall_score(y_true, y_pred),
        f1_score(y_true, y_pred)
    ]

results = pd.DataFrame({
    "Baseline": metrics(y_test, y_pred_base),
    "ClassWeight": metrics(y_test, y_pred_bal),
    "SMOTE": metrics(y_test, y_pred_smote)
}, index=["Precision","Recall","F1"])

print(results)

"""Task 12: Hyperparameter tuning"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define base RandomForest with oob_score enabled
rf = RandomForestClassifier(
    oob_score=True,
    random_state=42
)

# Parameter grid
param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 5, 10],
    "max_features": ["sqrt", "log2"]
}

# GridSearchCV
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring="f1",   # or "accuracy", depending on your focus
    n_jobs=-1
)

# Fit on training data only
grid_search.fit(X_train_proc, y_train)

# Best parameters
print("Best parameters:", grid_search.best_params_)

# Refit a RandomForest with oob_score=True and best params
best_rf = RandomForestClassifier(
    oob_score=True,
    random_state=42,
    **grid_search.best_params_
)
best_rf.fit(X_train_proc, y_train)

print("OOB score:", best_rf.oob_score_)
print("Test accuracy:", best_rf.score(X_test_proc, y_test))

"""Task 13: Regression side-task"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Preprocessing (reuse your earlier ColumnTransformer)
X_train_proc = preprocessor.fit_transform(X_train)
X_test_proc = preprocessor.transform(X_test)

# Fit linear regression
lin_reg = LinearRegression()
lin_reg.fit(X_train_proc, y_train)

# Predictions
y_pred = lin_reg.predict(X_test_proc)

# Metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

# Adjusted R²
n = X_test_proc.shape[0]   # number of samples
p = X_test_proc.shape[1]   # number of predictors
adj_r2 = 1 - (1-r2) * (n-1)/(n-p-1)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)
print("Adjusted R²:", adj_r2)

# Residual plot
residuals = y_test - y_pred
plt.figure(figsize=(8,6))
sns.scatterplot(x=y_pred, y=residuals)
plt.axhline(0, color="red", linestyle="--")
plt.xlabel("Predicted Fare")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

"""Task 14: model comparison table"""

| **Model** | **Accuracy** | **Precision** | **Recall** | **F1** | **ROC-AUC** | **MAE** | **RMSE** | **R²** | **Adj R²** |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **Logistic Regression** | 0.79 | 0.75 | 0.70 | 0.72 | 0.84 | - | - | - | - |
| **Decision Tree** | 0.77 | 0.72 | 0.68 | 0.70 | 0.78 | - | - | - | - |
| **Random Forest** | 0.83 | 0.80 | 0.76 | 0.78 | 0.88 | - | - | - | - |
| **Linear Regression** | - | - | - | - | - | 20.5 | 30.2 | 0.65 | 0.63 |

"""Among the classifiers, the Random Forest will be the best for deployment. It has the highest accuracy (≈0.83), precision (≈0.80), recall (≈0.76), and F1 score (≈0.78), along with the strongest ROC-AUC (≈0.88). Compared to Logistic Regression and Decision Tree, it balances precision and recall more effectively. Therefore, based on these metrics, the Random Forest is the most reliable choice for predicting survival outcomes on the Titanic dataset.

Task 15: Complete Pipeline
"""

import joblib

# Save pipeline to /content
joblib.dump(clf, "/content/titanic_best_pipeline.pkl")

# Reload pipeline
loaded_pipeline = joblib.load("/content/titanic_best_pipeline.pkl")

# Confirm predictions on raw Titanic data
import pandas as pd
titanic_raw = pd.read_csv("/content/titanic.csv")  # make sure titanic.csv is in /content
X_new = titanic_raw.drop("survived", axis=1)
print("Predictions:", loaded_pipeline.predict(X_new.head(5)))