# -*- coding: utf-8 -*-
"""Capstone_Module_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCdgPk47vCuCcrb1NE1KL_jelP3NCJbg
"""

pip install requests

pip install beautifulsoup4

import numpy as np
import pandas as pd

"""Task 1: Scraping the data from books.toscrape.com"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

base_url = "http://books.toscrape.com/catalogue/page-{}.html"

books = []

for page in range(1, 6):  # scrape first 5 pages
    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    for book in soup.select("article.product_pod"):
        title = book.h3.a["title"]
        price = book.select_one("p.price_color").text
        star_rating = book.p["class"][1]
        availability = book.select_one("p.availability").text.strip()


        book_url = "http://books.toscrape.com/catalogue/" + book.h3.a["href"]
        book_response = requests.get(book_url)
        book_soup = BeautifulSoup(book_response.text, "html.parser")

        breadcrumb = book_soup.select("ul.breadcrumb li a")
        if len(breadcrumb) >=3:
          category = breadcrumb[2].text.strip()

        books.append({
            "title": title,
            "price": price,
            "star_rating": star_rating,
            "availability": availability,
            "category": category
        })

print(f"Scraped {len(books)} books")

df = pd.DataFrame(books)
df.head()

df.info()

df.describe()

df['category'].unique()

"""Task 2: cleaning the scraped fields into proper types

1. Strip the currency symbol from price and convert it to a float column price_gbp.
2. Convert the text star rating (One…Five) into an integer column rating (1–5).
3. Parse the availability text into a boolean column in_stock.
4. If any field fails to parse for a given row (e.g., unexpected text), handle it with the median-imputation approach for numeric fields or drop the row (state and justify your choice) — do not leave the pipeline crashing on messy rows.
"""

df['price_gbp'] = df['price'].str.replace("Â£","").astype(float)

rating = {"One":1, "Two": 2, "Three":3, "Four":4, "Five":5}
df['rating'] = df['star_rating'].map(rating)

df['in_stock'] = df['availability'].str.contains('In stock')

df["price_gbp"] = pd.to_numeric(df["price_gbp"], errors="coerce")
median_price = df["price_gbp"].median()
df["price_gbp"].fillna(median_price, inplace=True)

df["rating"] = pd.to_numeric(df["rating"], errors="coerce")
median_rating = df["rating"].median()
df["rating"].fillna(median_rating, inplace=True)

df.dropna(subset=["in_stock", "category"], inplace=True)

df.head()

"""Task 3: convert price_gbp into price_inr, 1 GBP = 105.50 INR."""

df['price_inr'] = df['price_gbp'] * 105.50

df.head()

"""Task 4: creating sql tables"""

import sqlite3
conn = sqlite3.connect('books.db')
cursor = conn.cursor()
cursor.execute("""
  create table IF NOT EXISTS categories (
    category_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name TEXT UNIQUE NOT NULL
)
  """)
conn.commit()
conn.close()

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
cursor.execute("""
  create table IF NOT EXISTS books (
    book_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT NOT NULL,
    price_gbp   INT NOT NULL,
    price_inr   REAL NOT NULL,
    rating      INTEGER CHECK(rating BETWEEN 1 AND 5),
    in_stock    BOOLEAN CHECK(in_stock IN (0,1)),
    category_id INTEGER NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
)
  """)
conn.commit()
conn.close()

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
tables = cursor.execute('''select name from sqlite_master where type='table' ''')
result = cursor.fetchall()
print(result)
conn.close()

with sqlite3.connect("books.db") as conn:
  cursor = conn.cursor()

for cat in df["category"].unique():
    cursor.execute("INSERT INTO categories (category_name) VALUES (?)", (cat,))

cursor.execute("SELECT category_id, category_name FROM categories")
cat_map = {name: cid for cid, name in cursor.fetchall()}

rows = [
    (row["title"], row["price_gbp"], row["price_inr"], row["rating"], int(row["in_stock"]), cat_map[row["category"]])
    for _, row in df.iterrows()
]

cursor.executemany("""
    INSERT INTO books (title, price_gbp, price_inr, rating, in_stock, category_id)
    VALUES (?, ?, ?, ?, ?, ?)
""", rows)

conn.commit()

cursor.execute("SELECT * FROM categories")
print(cursor.fetchall())

cursor.execute("SELECT * FROM books")
print(cursor.fetchall())

"""Task 5: sql queries to fetch data from the created tables"""

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
tables = cursor.execute('''select title, price_inr from books where rating= 5 ''')
result = cursor.fetchall()
print(result)
conn.close()

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
tables = cursor.execute('''select * from books order by price_inr desc LIMIT 10 ''')
result = cursor.fetchall()
print(result)
conn.close()

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
tables = cursor.execute('''select distinct title from books ''')
result = cursor.fetchall()
print(result)
conn.close()

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
tables = cursor.execute('''select title, price_inr, rating from books where price_inr between 1000 and 2000  and rating in (4,5)''')
result = cursor.fetchall()
print(result)
conn.close()

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
tables = cursor.execute('''select category_name, sum(price_inr) as price from books b join categories c on c.category_id = b.category_id
group by category_name''')
result = cursor.fetchall()
print(result)
conn.close()

conn = sqlite3.connect('books.db')
cursor = conn.cursor()
tables = cursor.execute('''select category_name, price_inr, rating from books b join categories c on c.category_id = b.category_id
order by category_name, rating desc limit 10''')
result = cursor.fetchall()
print(result)
conn.close()

"""Task 6: Reading query results into pandas dataframe"""

conn = sqlite3.connect('books.db')
df_rating = pd.read_sql('''select title, price_inr from books where rating= 5 ''', conn)
print(df_rating.head())
conn.close()

conn = sqlite3.connect('books.db')
df_join = pd.read_sql('''select category_name, title, price_inr, rating from books b join categories c on c.category_id = b.category_id
order by category_name, rating desc limit 10 ''', conn)
print(df_join.head(10))
conn.close()

conn = sqlite3.connect('books.db')
df_books = pd.read_sql('select * from books', conn)
df_categories = pd.read_sql('select * from categories', conn)

print(df_books.head())
print(df_categories.head())

df_merge = pd.merge(df_books, df_categories, on = 'category_id', how = 'inner')[['category_name','title','price_inr','rating']]
df_merge.head()

df_merge_sort = df_merge.sort_values(by=['category_name','rating'], ascending = [True, False])
df_merge_sort.head(10)